services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: jose
      POSTGRES_PASSWORD: josepass
      POSTGRES_DB: nestdb
    ports:
      - 5499:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jose -d nestdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: "postgresql://jose:josepass@db:5432/nestdb?schema=public"
      API_KEY: "my-secret-api-key"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8085:80
    environment:
      VITE_API_URL: "http://localhost:3000/api"
    depends_on:
      - app